//CRIAÇÃO DE VARIÁVEL PARA RECEBER ID DO CANVAS


//VARIÁVEL QUE BUSCA CONTEXTO DO CANVAS PARA CRIAR ITENS EM 2D


//ALTERAÇÃO DE COR O PRIMEIRO OBJETO
 
//INICIAR O MODO CANETA

//ALTERAR A COR DO OBJETO

//ALTERAR A LARGURA DA LINHA DO OBJETO

//CRIAR UM CÍRCULO, COMO PI É METADE DE UM CÍRCULO, FOI MULTIPLICADO POR 2

//CRIA A LINHA DO DESENHO DO CÍRCULO


//CHAMAR EVENTO PARA FAZER A FUNÇÃO DE CLICK


//FUNÇÃO DE CLICK
function myMousedown(e)
{
    //VARIÁVEL RECEBE A COR DA CAIXA DE TEXTO EM INGLÊS
   
    //MOSTRA NA ÁREA DO PROGRAMADOR NO SITE - INSPECIONAR
    
    
    //VARIÁVEIS CRIADAS PARA RECEBER AS POSIÇÕES X E Y DIMINUINDO PELA ÁREA DO CANVAS
    
    

    //MOSTRAR NA ÁREA DO PROGRAMADOR AS POSIÇÃO DE X E Y
    

    //CHAMANDO O CÍRCULO NAS POSIÇÕES CORRETAS DE X E Y
        
}

//FUNÇÃO DO CÍRCULO
function circle(mouseX , mouseY){
    
    //MESMO PROCESSO DO 1 CÍRCULO ESTÁTICO CRIADO ACIMA
   
}

//FUNÇÃO PARA LIMPAR ÁREA
function clearArea(){
    
    //VARIÁVEL SENDO CHAMADA PARA FAZER O PROCESSO DE LIMPEZA COM clearRect
    
}



